blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/unascribed/Fabrication-Features/issues/new
    about: Feature requests, ideas, questions, etc go here.
